### ISSUE TITLE
Ability to bind standard S.op() functions

### ISSUE THREAD

**Issue by rr326** [lunixbochs/reslate#10]
Here's a standard slate.js binding: `S.bind('z:cmd;ctrl;alt',S.op("resize", { "width" : "+10%", "height" : "+0" }) );`

If I do that before I call `S.src('.reslate.js')`, it works fine.  If I do it after, it doesn't work.  It looks like I can wrap in a function(){} and then do tmp=S.op..; tmp.run(); but that's all quite ugly. 

I kinda get why, and I even think I see how one might fix it, but all this deep javascript coding is quite frankly beyond my depth. 

It looks like if you added a new test in makeCallback() to see if op is a `JSOperationWrapper` then you could call it directly, and without wrapping further. But I'm stuck - I can't figure out how to test it properly. (My attempts with instanceof and isPrototypeOf didn't work.)

**Comment by lunixbochs** [comment]
Your theory seems sound. Slate has underscore.js available, which is a bit better at some introspection mechanics. You might find a function in Underscore that will help.

**Comment by rr326** [comment]
I couldn't get direct access to the JSOperationWrapper - its a cruntime object outside the js framework so I couldn't get info on the source object, type, etc. 

So I did this:
In reslate.js

```
    wrap: function(opcall) {
        // Slate preprocesses the .slate.js file and returns pointers to cruntime objects (JSOperationWrapper type)
        // In your .slate.js you could do (ina bind): 
        //   z: function(win) {tmp=S.op("resize", { "width" : "+0", "height" : "+10" }); tmp.run();}
        // Or you can use this wrapper function.
        $.log('wrap called (wrapping S.op() call)');
        return function(win) {
            opcall.run();
        };
    }, 
```

In a .slate.js (in a bind):

```
    b: $.wrap(S.op("resize", { "width" : "+0", "height" : "+10" })),
```

Will do a pull request when I'm done with any other changes.

**Comment by lunixbochs** [comment]
To follow the style thus far, honestly I'd prefer `b: $.op('resize', etc)`

But you could probably also check if `X.run` is a valid function using underscore.

**Comment by rr326** [comment]
Done. See pull request for more info.

(though didn't understand your last point about X.run)
