### ISSUE TITLE
In the readme, describe what reslate does

### ISSUE THREAD

**Issue by philc** [lunixbochs/reslate#5]
To understand what this is, one has to read through the source, and even then it's not clear what the overall benefit is.

**Comment by lunixbochs** [comment]
I think the high points include:
- Concise configuration.
- Extensibility - it wraps the Screen, Window, and Rect objects into proxy classes. You can extend these classes pretty easily in reslate.js.
- Many convenience methods:
  - Reslate will take most object types in a binding and make sense of them.
  - Nested object syntax for binding hotkeys (reduces need for repetition).
  - Array syntax will do a `slate.chain` for you.
  - Strings automatically map to slate's "operation" objects.
  - The `slate.bindAll` in `slate.example.js` is a good example of this.
- Works around some issues in Slate:
  - It's harder to lose a window offscreen.
  - Some useless popups are silenced.
- When you hit an exception, you're provided with a full traceback if possible. You can also use $.backtrace to generate one yourself.
- The $ object ( https://github.com/lunixbochs/reslate/blob/master/reslate.js#L36 )

You can also compare the example config with the stock slate example.
