### ISSUE TITLE
Toss / focus not working

### ISSUE THREAD

**Issue by rr326** [lunixbochs/reslate#8]
I'm reluctant to call this an 'issue' since it's probably my fault, but I've set up your .reslate.js and example .slate.js.  Hyper+ hjkl... all work as expected.  The toss / throw / focus functions  do nothing and I have no idea why. (I have two monitors, btw.)

One oddity - console shows every time I reload:

```
6/11/14 5:22:20.935 PM WindowServer[94]: CGXSetWindowListSystemAlpha: Invalid window 6478 (index 0/1)
6/11/14 5:22:20.935 PM WindowServer[94]: CGXSetWindowListSystemAlpha: Invalid window 6479 (index 0/1)
```

One other:
`y: [S.log('hyper y hit'), $('corner', 'top-left'),
            $('corner', 'top-left', 1.5)],`
Adding that log line does nothing. It doesn't break the movements, but no log is shown.  (I have no idea if this gives info.) 

Any ideas?

I guess I could go vanilla slate.js, but this is super slick, and I'm hooked.

**Comment by rr326** [comment]
Woops, my bad. My hyper was mapped to shift hyper, so only the shift-based keystrokes worked.  Sorry.

**Comment by lunixbochs** [comment]
As for the S.log, the entire `.slate.js` is executed as JavaScript before it gets to me. I don't get to play any parser tricks or delay execution.

That means `S.log('hyper y hit')` would only ever work (regardless of keystrokes) if you put it in a callback function, like so: `function(win) { S.log('hyper y hit') }`
