### ISSUE TITLE
Silent Failures

### ISSUE THREAD

**Issue by rr326** [lunixbochs/reslate#9]
I was debugging some strange behavior, and basically I could do something slightly wrong and slate would reload, but not actually reload.  It would LOOK like it reloaded, but my debug lines in the .slate.js would not print and no keys would be active. And even intentional js errors (like: `var x = ksjdfljsl.slkdfjls.skljds;`) would not throw an exception. 

One thing I'm certain caused this:

```
 u:   [$('corner', 'top-left', 2,   //  <-- Notice the missing right paren
          $('corner', 'top-left', 1.5),
          $('corner', 'top-left', 3)],
```

Another one, even more baffling (and harder to reproduce) is I had a `barResize` or a `corner` without a size (eg `$('barResize', 'left'),`) and that caused the silent fail.  But normally this works, and I haven't been able to reproduce, but could put more time in if needed.  (Though, perhaps I had another syntax error - it might have been `$('barResize', 'left', ), //<-- See the hanging comma` - that DOES create a silent fail and would be consistent with the above problem.)

**Comment by lunixbochs** [comment]
That's probably an issue with Slate. I can't do anything with syntax errors.

**Comment by rr326** [comment]
Gotcha.  I'll try to reprodce a reslate-free version and post to slate.

Since there is nowhere else to say this, I'd just like to say that I think
reslate is really fantastic.  Nice work.

**Comment by rr326** [comment]
Sorry to pester you.  And I know this is not the right place to ask a question, but where is?

Question: How do I call a standard slate S.op() call within one of your binds or chains?

eg - None of these work. :

```
hyper: {
    shift: {
         j:  S.op("resize", { "width" : "-10%", "height" : "+0" }),
         k: function(win) {S.op("resize", { "width" : "-10%", "height" : "+0" })},
         j:  [S.op("resize", { "width" : "-10%", "height" : "+0" })],


    },
```

**Comment by rr326** [comment]
I'll close this and write a proper issue, now that I understand this.
